name: utoe-neural-falsification
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy=1.24
  - pandas=2.0
  - scipy=1.10
  - scikit-learn=1.2
  - statsmodels=0.14
  - nilearn=0.10.1
  - nibabel=5.1
  - joblib=1.3.2
